# generated by Neptune Namespaces v3.x.x
# file: Art.DataStructures/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.DataStructures', class DataStructures extends Neptune.PackageNamespace
  @version: require('../../package.json').version
