# generated by Neptune Namespaces v3.x.x
# file: tests/Art.DataStructures/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.DataStructures', class DataStructures extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
